
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from email import message
from pathlib import Path
import main
import func as fn
import barcode

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)





window = Tk()

window.geometry("428x926")
window.configure(bg = "#FFFFFF")


def OnEnterEvent(e):
    # messagebox.showinfo('title','test')

    if entry_1.get() == "":
        messagebox.showerror('Error','Please input a product on the search bar.')
    else:
        if main.SearchQuery(entry_1.get()) == None:
            messagebox.showinfo('Did you know?',fn.ReturnFact(entry_1.get()))
        else:
            messagebox.showerror('Error','Not found')

def BarcodeScanner():
    messagebox.showinfo('Product',barcode.BarcodeReader('innometa.png'))
        




window.bind('<Return>',OnEnterEvent)


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 926,
    width = 428,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

# canvas.place(x = 0, y = 0)
# canvas.create_rectangle(
#     0.0,
#     0.0,
#     428.0,
#     926.0,
#     fill="#000000",
#     outline="")

canvas.create_rectangle(
    156.0,
    42.0,
    272.0,
    107.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    35.0,
    15.0,
    392.76611328125,
    29.24542236328125,
    fill="#000000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    214.0,
    155.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=2
)
entry_1.place(
    x=35.0,
    y=131.0,
    width=358.0,
    height=46.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=BarcodeScanner,
    relief="flat"
)
button_1.place(
    x=42.0,
    y=433.0,
    width=343.0,
    height=56.0
)
window.resizable(False, False)
window.mainloop()
